//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int stu_id { get; set; }
        public string stu_name { get; set; }
        public string stu_gender { get; set; }
        public Nullable<int> stu_age { get; set; }
        public string stu_subject { get; set; }
    }
}
